---
hostPort: %host%:%port%
ssl: false
lowercaseOutputLabelNames: true
lowercaseOutputName: true

rules:
- pattern: category=(.*), scope=updateHandler, name=(org.apache.solr.update.*><>(adds|autocommits|commits|cumulative_adds|cumulative_deletesById|cumulative_deletesByQuery|cumulative_errors|deletesById|deletesByQuery|docsPending|errors|expungeDeletes|optimizes|rollbacks|soft autocommits))
  name: solr_core_$3
  labels:
    category: $1
    scope: updateHandler
    name: $2
  type: COUNTER

- pattern: name=org.apache.solr.handler.*><>(15minRateReqsPerSecond|5minRateReqsPerSecond|75thPcRequestTime|95thPcRequestTime|999thPcRequestTime|99thPcRequestTime|avgRequestsPerSecond|avgTimePerRequest|medianRequestTime)

- pattern: category=(.*), scope=(.*), name=(org.apache.solr.handler.*><>(errors|handlerStart|requests|timeouts|totalTime))
  name: solr_core_$4
  labels:
    category: $1
    scope: $2
    name: $3
  type: COUNTER

- pattern: category=CACHE, scope=(.*), name=org.apache.solr.search.(FastLRUCache|LRUCache)><>(size|warmupTime)

- pattern: category=CACHE, scope=(.*), name=(org.apache.solr.search.(FastLRUCache|LRUCache)><>(cumulative_evictions|cumulative_hitratio|cumulative_hits|cumulative_inserts|cumulative_lookups|evictions|hitratio|hits|inserts|lookups))
  name: solr_core_$4
  labels:
    category: CACHE
    scope: $1
    name: $2
  type: COUNTER

- pattern: category=(.*), scope=searcher, name=(org.apache.solr.search.SolrIndexSearcher><>(deletedDocs))
  name: solr_core_$3
  labels:
    category: $1
    scope: searcher
    name: $2
  type: COUNTER

- pattern: scope=searcher, name=org.apache.solr.search.SolrIndexSearcher><>(maxDoc|numDoc|warmupTime)
